version: "3.8"
name: agenda_saramago
services:
  database:
    image: mysql:8.0.33
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq
    env_file:
      - .env

  api:
    build: agenda-saramago/
    env_file:
      - .env
    depends_on:
      - database
      - rabbitmq
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://database:${MYSQL_PORT}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQL_USER",
        "spring.datasource.password" : "$MYSQL_PASSWORD",
        "spring.datasource.hibernate.dialect":"org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.rabbitmq.host":"rabbitmq",
        "spring.rabbitmq.port":"${RABBIT_PORT}",
        "spring.rabbitmq.username":"${RABBIT_USER}",
        "spring.rabbitmq.password":"${RABBIT_USER}"
        }'

  data_gen:
    build: data_gen/
    
    env_file:
      - .env
    environment:
      - RABBIT_HOST=rabbitmq
      - RABBIT_PORT=${RABBIT_PORT}
      - RABBIT_USER=${RABBIT_USER}
      - RABBIT_PASSWORD=${RABBIT_PASSWORD}
    depends_on:
      - api
      - rabbitmq
    command: >
      sh -c "
        echo 'Esperando 10 segundos antes de iniciar...';
        sleep 10;
        exec python3 main.py 10
      "

  web:
    build: prototype/agenda_saramago/
    depends_on:
      - api
    environment:
      - VITE_API_URL=${VITE_API_URL}

  proxy:
    build: proxy/
    ports:
      - 80:80
    depends_on:
      - api
      - web
